config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :private do
    resources :articles

    namespace :settings do
      resource :withdrawals
      resource :profiles
      resource :accounts
      resource :passwords
    end
  end


  #scope 'user' do
  #  scope module: :publish do
  #    resource :articles, only: [:index, :show]
  #  end
  #end


  scope module: :publish do
  #namespace :publish do
    resources :comments
  end
  #scope module: :publish do
  #  scope 'user' do
  #    resources :articles, only: [:index, :show]
  #  end
  #end

  #scope module: :publish do
  #  scope 'user' do
  #    resource :articles
  #  end
  #end


  #resources :user, only: [:index, :show] do
  #  scope module: :publish do
  #    resources :articles, only: [:index, :show] do
  #    end
  #  end 
  #end


  resources :user, only: [:index, :show] do
    scope module: :publish do
      resources :articles, only: [:index, :show]
    end 
  end

  #devise_for :users,
  #  controllers: {
  #    registrations: 'regists',
  #  }
  #
  
  #resources :user, only: [:index, :show] do
  #  scope module: :publish do
  #    resoures :articles, only: [:index, :show]
  #  end
  #end

  #resources 
  devise_for :users,
    controllers: {
      registrations: 'regists',
      omniauth_callbacks: 'omniauth_callbacks',
    }

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.haml
- content_for(:container_class, 'dummy-container')

.jumbotron.text-center{style: 'margin-top: -20px;'}
  %h1
    Ruby On Railsで作った<br>ブログサービスのサンプルサイトです

%div.text-center
  = link_to '始める', new_user_registration_path, class: 'btn btn-success btn-lg'

.container
  .row
    .col-sm-12
      %h4
        最近記事
      - Article.limit(10).each do |article |
        .list-group
          = link_to user_article_path(article.user.user_nickname,article), class: 'list-group-item' do
            %h4.list-group-item-heading
              = article.title
            %p.list-group-item-text
              = truncate article.body_source
            %div
              .pull-right