config/routes.rb
Rails.application.routes.draw do
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  scope module: :private do
    resources :articles

    namespace :settings do
      resource :withdrawals
      resource :profiles
      resource :accounts
      resource :passwords
    end
  end


  #scope 'user' do
  #  scope module: :publish do
  #    resource :articles, only: [:index, :show]
  #  end
  #end


  scope module: :publish do
  #namespace :publish do
    resources :comments
  end
  #scope module: :publish do
  #  scope 'user' do
  #    resources :articles, only: [:index, :show]
  #  end
  #end

  #scope module: :publish do
  #  scope 'user' do
  #    resource :articles
  #  end
  #end


  #resources :user, only: [:index, :show] do
  #  scope module: :publish do
  #    resources :articles, only: [:index, :show] do
  #    end
  #  end 
  #end


  resources :user, only: [:index, :show] do
    scope module: :publish do
      resources :articles, only: [:index, :show]
    end 
  end

  #devise_for :users,
  #  controllers: {
  #    registrations: 'regists',
  #  }
  #
  
  #resources :user, only: [:index, :show] do
  #  scope module: :publish do
  #    resoures :articles, only: [:index, :show]
  #  end
  #end

  #resources 
  devise_for :users,
    controllers: {
      registrations: 'regists',
      omniauth_callbacks: 'omniauth_callbacks',
    }

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include AASM

  aasm do
    state :draft, :initial => true
    state :published

    #event :publish, before: ->{ self.published_at = Time.now } do
    event :publish do
      transitions :from => :draft, :to => :published

    end

    event :draft do
      transitions :from => :published, :to => :draft
    end

  end

  has_many :comments
  belongs_to :user
end

app/models/change_password.rb
class ChangePassword
  include ActiveModel::Model

  attr_accessor :current_password, :new_password, :new_password_confirmation 

  validates :current_password, presence: true
  validates :new_password, presence: true
  validates :new_password_confirmation, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
  # TODO: これなくても動いたのでとりあえずコメントアウトしました。
  #, :omniauth_providers => [:twitter]

  has_many :articles
  has_many :comments

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing_profile_img.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/


def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(user_nickname:     auth.info.nickname,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    User.create_unique_email,
                         password: Devise.friendly_token[0,20]
                        )
    end
    user
  end

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(user_nickname:     auth.extra.raw_info.name,
                         provider: auth.provider,
                         uid:      auth.uid,
                         email:    auth.info.email,
                         password: Devise.friendly_token[0,20]
                        )
    end
    user
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.create_unique_email
    User.create_unique_string + "@example.com"
  end

  #def self.from_omniauth(auth)
    # providerとuidでUserレコードを取得する
    # 存在しない場合は、ブロック内のコードを実行して作成する
    #where(auth.slice(:provider, :uid)).first_or_create do |user|
  #  where(provider: auth["provider"], uid: auth["uid"]).first_or_create do |user|
  #    user.provider = auth["provider"]
  #    user.uid = auth["uid"]
      #user.username = auth["info"]["nickname"]
      #user.username = auth.info.nickname
  #  end
  #end

  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      #new(session["devise.user_attributes"], without_protection: true) do |user|
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def twitter
    puts "twitter---------------"
    # providerとuidでuserレコードを検索。存在しなければ、新たに作成する
    #@user = User.from_omniauth(request.env["omniauth.auth"].except("extra"))
    #
    @user = User.find_for_twitter_oauth(request.env["omniauth.auth"], current_user)

    # userレコードが既に保存されているか
    if @user.persisted?
    #if @user.persisted?
      # ログインに成功
      flash.notice = "Signed in!"
      sign_in_and_redirect @user
      #new_user_registration @user
    else
      #存在してなかったので新しくアカウントを作る
      #user.save
      puts "ssssssssssss elseslelele"
      puts @user.attributes
      flash.notice = "Created account!"
      session["devise.user_attributes"] = @user.attributes
      
      redirect_to new_user_registration_url
      #sign_in_and_redirect(user) and return
    end
  end

  #alias_method :twitter, :all
  #alias_method :facebook, :all
  #alias_method :github, :all
end

app/controllers/regists_controller.rb
class RegistsController < Devise::RegistrationsController 
  def new
    build_resource({})
    respond_with self.resource

  end

  def create
    puts 'testtest'
    build_resource(sign_up_params)
    resource.save


  end

  private
  def sign_up_params
    params.require(:user).permit(:user_nickname, :email, :password, :password_confirmation)
  end

  def after_sign_up_path_for(resource)
    root_path 
  end

  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/controllers/withdraw_controller.rb
class WithdrawController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/private/articles_helper.rb
module Private::ArticlesHelper
end

app/helpers/regists_helper.rb
module RegistsHelper
end

app/helpers/resits_helper.rb
module ResitsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/withdraw_helper.rb
module WithdrawHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rails51BlogSample
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body



    %nav.navbar.navbar-default{:role => "navigation"}
      .container-fluid
        .navbar-header
          %buttion.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{:href => '/'} RAILS BLOG SAMPLE!

        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li
                = link_to '+ 新しい記事を作成する', new_article_path
              %li
                = link_to edit_settings_profiles_path, style: 'padding-right: 10px;' do
                  = image_tag current_user.avatar(:thumb), width: 20, height: 20
                  = current_user.user_nickname
              %li.dropdown
                = link_to '#', class: 'dropdown-toggle', 'data-toggle' => 'dropdown', style: 'padding-left: 10px;' do
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to 'プロフィール設定', edit_settings_profiles_path 
                  %li.divider
                  %li= link_to 'ログアウト', destroy_user_session_path(:authenticity_token => form_authenticity_token()), method: :delete
            - else
              %li= link_to 'はじめる', new_user_registration_path
              %li= link_to 'ログイン', new_user_session_path
              %li= link_to 'twitterログイン', user_twitter_omniauth_authorize_path 
              %li= link_to 'facebookログイン', user_facebook_omniauth_authorize_path 
  .container
    = render partial: 'shared/breadcrumbs'
    //%ol.breadcrumbs
    //%ol.breadcrumb
    //  = breadcrumbs
  .container
    - flash.each do |type, msg|
      %div{class: "alert alert-#{type}"}=msg

  %div{class: content_for?(:container_lcass) ? yield(:container_class) : 'container'}
    = yield
  
  %footer.text-center
    %div
      作った人：negabaro kim
    %div
      #{link_to 'Twitter', 'https://twitter.com/negabaro', target: :_blank} | #{link_to 'FB', 'https://www.facebook.com/negabaro', target: :_blank}

app/views/shared/_breadcrumbs.html.haml
- if breadcrumbs.empty?
- else
  %ol.breadcrumb
    = breadcrumbs